version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=sbm
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - springboot-db-net

  application:
    build: .
    depends_on:
      - mysqldb   # ✅ fixed
    ports:
      - "8080:8080"
    networks:
      - springboot-db-net
    volumes:
      - /data/springboot-app

networks:
  springboot-db-net:

